name: Publish release artifacts

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghidra: [ '10.3', '10.2.2', '10.2.1', '10.2' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v2
        with:
          # gradle-version: 7.0
          arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
