name: Publish release artifacts

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghidra: [ '10.3', '10.3.1', '10.3.2' ]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@main
        with:
          # gradle-version: 7.0
          arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: Ghidra-Switch-Loader_${{ matrix.ghidra }}
          path: dist/*.zip
